name: meta-handle1
channels:
  - pytorch3d
  - pytorch
  - iopath
  - conda-forge
  - defaults
dependencies:
  - cudatoolkit=10.2.89
  - fvcore=0.1.3.post20210223
  - iopath=0.1.8
  - numpy=1.19.2
  - python=3.8.8
  - pytorch=1.7.1
  - pytorch3d=0.4.0
  - torchvision=0.8.2
  - tqdm=4.59.0
  - visdom=0.1.8.9
